import React from "react";
import styled from "styled-components";

// NATIVE-FIRST LABS.
//
// The canonical Live Activity previews are the REAL Swift renders, generated by
// the review harness (`cd PackApp && npm run live-activity:review`) into
// `manual-live-activity-review/index.html` — one manifest-driven page over every
// surface × state × phase (lock, Dynamic Island minimal/compact/expanded, the
// Smart Stack card, and both watch complications). The labs route embeds that
// gallery directly so there is a SINGLE native source of truth.
//
// This replaces the old TypeScript re-derivation of the surfaces (the parallel
// `src/labs/liveActivityModel` model + website-capture screenshots), which drifted
// from the shipping Swift and has been retired.
//
// The `/@fs/` path is Vite's filesystem serving (the review dir is on the
// server allow-list); this is an internal dev tool, so a dev-server absolute
// path is expected. Regenerate the gallery whenever the native Swift changes.
const NATIVE_GALLERY_URL =
  "/@fs/Users/noahmitsuhashi/Code/PackAll/PackApp/manual-live-activity-review/index.html";

const GalleryFrame = styled.iframe`
  border: 0;
  display: block;
  width: 100%;
  height: calc(100vh - 64px);
  background: #000;
`;

function LiveActivityLab(): React.JSX.Element {
  return (
    <GalleryFrame
      src={NATIVE_GALLERY_URL}
      title="Live Activity native gallery"
      loading="lazy"
    />
  );
}

export default LiveActivityLab;
