type GmailFilterBatchingOptions = {
  readonly maxDomainsPerRule: number;
  readonly maxQueryLength: number;
};

const DEFAULT_GMAIL_FILTER_BATCHING: GmailFilterBatchingOptions = {
  maxDomainsPerRule: 75,
  maxQueryLength: 1500,
};

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function toGmailFromQuery(domains: readonly string[]): string {
  const normalized = domains.map((domain) => domain.trim()).filter(Boolean);
  if (normalized.length === 0) {
    return "";
  }

  // Gmail search syntax supports grouping terms with braces as an OR-set, e.g.
  // `{from:amy from:david}`. Using repeated `from:` terms is more reliable than
  // `from:(a OR b)` when importing filters.
  if (normalized.length === 1) {
    return `from:@${normalized[0]}`;
  }

  return `{${normalized.map((domain) => `from:@${domain}`).join(" ")}}`;
}

function normalizeDomains(domains: readonly string[]): string[] {
  return Array.from(
    new Set(
      domains
        .map((domain) => domain.trim().toLowerCase())
        .filter((domain) => domain.length > 0)
    )
  );
}

function batchDomainsForGmail(
  domains: readonly string[],
  options: GmailFilterBatchingOptions = DEFAULT_GMAIL_FILTER_BATCHING
): string[][] {
  const normalizedDomains = normalizeDomains(domains);

  const batches: string[][] = [];
  let current: string[] = [];

  const flush = () => {
    if (current.length === 0) return;
    batches.push(current);
    current = [];
  };

  for (const domain of normalizedDomains) {
    const candidate = [...current, domain];
    const wouldExceedCount = candidate.length > options.maxDomainsPerRule;
    const wouldExceedLength = toGmailFromQuery(candidate).length > options.maxQueryLength;

    if (current.length > 0 && (wouldExceedCount || wouldExceedLength)) {
      flush();
      current.push(domain);
      continue;
    }

    current.push(domain);
  }

  flush();
  return batches;
}

export function buildGmailFiltersXml({
  domains,
  label,
  forwardTo,
  mode = "single",
}: {
  readonly domains: readonly string[];
  readonly label: string;
  readonly forwardTo?: string;
  readonly mode?: "batched" | "single";
}): { readonly xml: string; readonly batches: number; readonly domainCount: number } {
  const domainBatches =
    mode === "single" ? [normalizeDomains(domains)] : batchDomainsForGmail(domains);
  const lines: string[] = [];

  lines.push("<?xml version='1.0' encoding='UTF-8'?>");
  lines.push(
    "<feed xmlns='http://www.w3.org/2005/Atom' xmlns:apps='http://schemas.google.com/apps/2006'>"
  );
  lines.push("  <title>Mail Filters</title>");
  lines.push("  <!-- Generated by Pack. -->");
  lines.push(
    "  <!-- Note: Gmail may ignore 'forwardTo' on import; if so, edit the created filters in Gmail UI and select “Forward it to”. -->"
  );

  for (let index = 0; index < domainBatches.length; index += 1) {
    const batch = domainBatches[index];
    const query = toGmailFromQuery(batch);
    if (!query) {
      continue;
    }

    lines.push("  <entry>");
    lines.push("    <category term='filter'></category>");
    lines.push("    <title>Mail Filter</title>");
    lines.push("    <content></content>");
    lines.push(`    <apps:property name='hasTheWord' value='${escapeXml(query)}'/>`);
    lines.push(`    <apps:property name='label' value='${escapeXml(label)}'/>`);
    lines.push("    <apps:property name='shouldNeverSpam' value='true'/>");
    if (forwardTo) {
      lines.push(`    <apps:property name='forwardTo' value='${escapeXml(forwardTo)}'/>`);
    }
    lines.push(`    <!-- Batch ${index + 1}/${domainBatches.length}: ${batch.length} domains -->`);
    lines.push("  </entry>");
  }

  lines.push("</feed>");
  lines.push("");

  return {
    xml: lines.join("\n"),
    batches: domainBatches.length,
    domainCount: normalizeDomains(domains).length,
  };
}

export function buildExchangeOnlineInboxRulesScript({
  domains,
  forwardTo,
  mailboxPlaceholder,
  action = "redirect",
}: {
  readonly domains: readonly string[];
  readonly forwardTo: string;
  readonly mailboxPlaceholder: string;
  readonly action?: "forward" | "redirect";
}): string {
  const domainBatches = batchDomainsForGmail(domains, {
    maxDomainsPerRule: 120,
    maxQueryLength: 20000,
  });

  const lines: string[] = [];
  lines.push("# Generated by Pack.");
  lines.push("# For Microsoft 365 / Exchange Online (work or school accounts).");
  lines.push(
    "# Requires Exchange Online PowerShell: https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2"
  );
  lines.push("# Notes:");
  lines.push("# - Redirect keeps the original sender; Forward sends from the mailbox owner.");
  lines.push("# - External auto-forwarding may be blocked by tenant policy.");
  lines.push("");
  lines.push(`$Mailbox = '${mailboxPlaceholder}'`);
  lines.push(`$ForwardTo = '${forwardTo}'`);
  lines.push("");

  const actionFlag = action === "forward" ? "-ForwardTo" : "-RedirectTo";

  for (let index = 0; index < domainBatches.length; index += 1) {
    const batchNumber = index + 1;
    const name = `Pack Travel Domain ${action === "forward" ? "Forward" : "Redirect"} (${batchNumber}/${domainBatches.length})`;
    const fromContains = `@(${domainBatches[index].map((domain) => `'@${domain}'`).join(", ")})`;
    lines.push(`# ${domainBatches[index].length} domains`);
    lines.push(
      `New-InboxRule -Mailbox $Mailbox -Name '${name}' -FromAddressContainsWords ${fromContains} ${actionFlag} $ForwardTo -StopProcessingRules $false`
    );
    lines.push("");
  }

  return lines.join("\n");
}

export function buildGmailBackfillAppsScript({
  domains,
  forwardTo,
  sentLabel = "Pack/Backfilled",
  maxThreadsPerRun = 50,
}: {
  readonly domains: readonly string[];
  readonly forwardTo: string;
  readonly sentLabel?: string;
  readonly maxThreadsPerRun?: number;
}): string {
  const safeMax =
    Number.isFinite(maxThreadsPerRun) && maxThreadsPerRun > 0 ? Math.floor(maxThreadsPerRun) : 50;
  const domainBatches = batchDomainsForGmail(domains, DEFAULT_GMAIL_FILTER_BATCHING);

  return [
    "// Generated by Pack.",
    "// Purpose: privacy-first backfill of older travel emails WITHOUT granting Pack mailbox read access.",
    "// This runs in *your* Google account and forwards travel emails (by known travel domains) to Pack.",
    "// Notes:",
    "// - Gmail sending quotas apply. Start small (e.g. 25–50 threads per run).",
    "// - This forwards messages and marks threads with a \"sent\" label to avoid re-sending.",
    "// - Run multiple times until it reports 0 processed threads.",
    "",
    `const DONEAI_FORWARD_TO = '${forwardTo.split("'").join("\\'")}';`,
    `const DONEAI_SENT_LABEL = '${sentLabel.split("'").join("\\'")}';`,
    `const DONEAI_MAX_THREADS_PER_RUN = ${safeMax};`,
    `const DONEAI_DOMAIN_BATCHES = ${JSON.stringify(domainBatches)};`,
    "",
    "function doneaiBackfillTravelEmails() {",
    "  const sent = GmailApp.getUserLabelByName(DONEAI_SENT_LABEL) || GmailApp.createLabel(DONEAI_SENT_LABEL);",
    "  let remainingThreads = DONEAI_MAX_THREADS_PER_RUN;",
    "  let processedThreads = 0;",
    "  let forwardedMessages = 0;",
    "",
    "  for (const batch of DONEAI_DOMAIN_BATCHES) {",
    "    if (remainingThreads <= 0) {",
    "      break;",
    "    }",
    "",
    "    const query = `from:(${batch.join(\" OR \")})`;",
    "    const threads = GmailApp.search(query, 0, remainingThreads);",
    "",
    "    for (const thread of threads) {",
    "      if (remainingThreads <= 0) {",
    "        break;",
    "      }",
    "",
    "      const labels = thread.getLabels().map((label) => label.getName());",
    "      if (labels.includes(DONEAI_SENT_LABEL)) {",
    "        continue;",
    "      }",
    "",
    "      const messages = thread.getMessages();",
    "      for (const message of messages) {",
    "        // Forward the original email to Pack. Gmail will include the original headers/body.",
    "        message.forward(DONEAI_FORWARD_TO);",
    "        forwardedMessages += 1;",
    "      }",
    "",
    "      thread.addLabel(sent);",
    "      processedThreads += 1;",
    "      remainingThreads -= 1;",
    "    }",
    "  }",
    "",
    "  Logger.log(`Pack backfill complete. Threads processed: ${processedThreads}. Messages forwarded: ${forwardedMessages}.`);",
    "  Logger.log(`Tip: run again until \"Threads processed\" stays at 0.`);",
    "}",
    "",
    "function doneaiBackfillHelp() {",
    "  Logger.log(\"Pack backfill help:\");",
    "  Logger.log(\"1) Run doneaiBackfillTravelEmails()\");",
    "  Logger.log(\"2) Re-run multiple times until it reports 0 processed threads.\");",
    "  Logger.log(\"3) If you hit a quota, wait and try again later.\");",
    "}",
    "",
  ].join("\n");
}
